---
- name: Install and configure Nginx with SSL certificate
  hosts: web_server
  become: yes
  vars:
    domain: "qliu.ca"
    extract_path: "/home/mimi/Github/IaC/ansible/qliu_ca.crt"
    remote_cert_path: "/etc/ssl/certs"
    remote_key_path: "/etc/ssl/private"
    nginx_main_conf: "/etc/nginx/nginx.conf"
  tasks:
    - name: Update package cache
      dnf:
        name: '*'
        state: latest

    - name: Install tree package
      dnf:
        name: tree
        state: present

    - name: Ensure Nginx is installed
      dnf:
        name: nginx
        state: present
        update_cache: yes
        
    - name: Upload Nginx configuration file
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
        validate: 'nginx -t -c %s'

    - name: Copy certificate to the remote server
      copy:
        src: "{{ extract_path }}"
        dest: "{{ remote_cert_path }}/{{ domain }}.crt"
        owner: root
        group: root
        mode: '0644'

    - name: Ensure the certificate file has correct permissions
      file:
        path: "{{ remote_cert_path }}/{{ domain }}.crt"
        owner: root
        group: root
        mode: '0644'
    - name: Ensure the key file has correct permissions
      file:
        path: "{{ remote_key_path }}/{{ domain }}.key"
        owner: root
        group: root
        mode: '0644'

    - name: Remove default server block
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
    # Separate task or handler to validate Nginx configuration after changes
    - name: Validate Nginx configuration
      command: nginx -t
      register: nginx_validate_result
      ignore_errors: yes

    - name: Reload Nginx if configuration is valid
      systemd:
        name: nginx
        state: restarted
      when: nginx_validate_result.rc == 0 
    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
  handlers:
    - name: Reload Nginx if configuration is valid
      ansible.builtin.systemd:
        name: nginx
        state: restarted
