---
- name: Install a package on managed node
  hosts: web_server
  become: yes
  tasks:
    - name: Update yum cache
      dnf:
        name: '*'
        state: latest

    - name: Install tree package
      dnf:
        name: tree
        state: present

    - name: Ensure Nginx is installed
      dnf:
        name: nginx
        state: present
        update_cache: yes
        
    - name: Upload Nginx configuration file
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
        validate: 'nginx -t -c %s'

    - name: Remove default server block
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes